name = "hariom-builds"
main = ".open-next/worker.js"
compatibility_date = "2026-10-03"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

# Production custom domain
[[routes]]
pattern = "hariombuild.eu.cc"
custom_domain = true
