import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { getAllPosts, getPost } from '@/lib/blog';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://hariombuilds.eu.cc';
export function generateStaticParams(){ return getAllPosts().map(post=>({slug:post.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const post=getPost(slug); if(!post)return {}; return { title:post.title, description:post.description, keywords:post.keywords, authors:[{name:post.author}], alternates:{canonical:'/blog/'+post.slug}, openGraph:{type:'article',title:post.title,description:post.description,url:SITE_URL+'/blog/'+post.slug,publishedTime:post.publishedAt,modifiedTime:post.updatedAt,authors:[post.author]} }; }
function renderMarkdown(markdown:string){ return markdown.split(/\n\n+/).map((block,index)=>{ const t=block.trim(); if(!t)return null; if(t.startsWith('### '))return <h3 key={index}>{t.slice(4)}</h3>; if(t.startsWith('## '))return <h2 key={index}>{t.slice(3)}</h2>; if(t.startsWith('# '))return <h1 key={index}>{t.slice(2)}</h1>; if(t.startsWith('```'))return <pre key={index}><code>{t.replace(/^```[a-zA-Z0-9_-]*\n?/,'').replace(/\n?```$/,'')}</code></pre>; return <p key={index}>{t}</p>; }); }
export default async function BlogPostPage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const post=getPost(slug); if(!post)notFound(); const articleUrl=SITE_URL+'/blog/'+post.slug; const structuredData={'@context':'https://schema.org','@type':'Article',headline:post.title,description:post.description,datePublished:post.publishedAt,dateModified:post.updatedAt,author:{'@type':'Person',name:post.author},publisher:{'@type':'Organization',name:'Hariom Builds',url:SITE_URL},mainEntityOfPage:articleUrl,keywords:post.keywords}; return <main className="studio-shell" style={{padding:'120px 24px 80px'}}><article style={{maxWidth:860,margin:'0 auto'}}><p className="eyebrow">{post.category}</p><h1>{post.title}</h1><p>{post.description}</p><small>By {post.author} · {post.publishedAt} · {post.readTime} min read</small><div className="prose" style={{marginTop:48}}>{renderMarkdown(post.body)}</div>{post.sources.length>0&&<aside style={{marginTop:56}}><h2>Sources & further reading</h2><ul>{post.sources.map(source=><li key={source.url}><a href={source.url} rel="nofollow noopener noreferrer">{source.title}</a></li>)}</ul></aside>}</article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/></main>; }
